class TextChunker:
    # Note: As the unit is the number of characters, these values (max_chunk_size & overlap) are small.
    # It is recommended to compare max_chunk_size/overlap: 100/10 150/20 200/30
    def __init__(self, max_chunk_size:int=100, overlap:int=10, cutting_type:str='mark', dataset_path_title:str="./data/kb_chunks_datasets"):
        self.max_chunk_size = max_chunk_size
        self.overlap = overlap
        self.cutting_type = cutting_type
        self.final_chunks = []
        self.dataset_path = f"{dataset_path_title}_{cutting_type}_{max_chunk_size}_{overlap}"  # 原始：mark-100-10
        self.knowledge_text_base = """
        OpenGauss is an enterprise-grade relational database that can also be used as a vector store for retrieval-augmented generation systems. In a RetrievalQA pipeline, the database is not only responsible for storing original text chunks, but also for storing the embedding vectors that represent the semantic meaning of those chunks. When a user submits a question, the system converts the question into an embedding vector and performs similarity search against the stored vectors. The most relevant chunks are then returned as retrieval context for answer generation. This architecture makes it possible to build a complete retrieval and question answering workflow on top of a database system instead of relying only on an in-memory vector engine.

        A typical RetrievalQA workflow contains several stages. The first stage is raw document preparation. Source documents may come from manuals, technical reports, markdown files, project notes, or deployment guides. These documents are often too long to be embedded directly, so they must be divided into smaller chunks. Chunking strategy has a direct influence on retrieval quality. If chunks are too short, important context may be lost. If chunks are too long, retrieval may become noisy because a returned chunk can contain both relevant and irrelevant content. In practice, chunk size and chunk overlap should be treated as tunable parameters. Common choices include chunk sizes of one hundred, three hundred, or five hundred words or tokens, with overlaps ranging from zero to one hundred. The best configuration depends on the structure of the source document and the nature of the user queries.

        After chunking, the next stage is embedding generation. An embedding model converts each text chunk into a dense numerical vector. In this project, the embedding layer may come from HuggingFace local models or Cohere hosted models. HuggingFace models are suitable when local execution and offline control are important. They can be integrated directly into Python code and deployed inside containers, which makes them useful for experiments on AArch64 platforms. However, model size, inference latency, and memory usage can become critical on resource-constrained devices. Cohere embeddings, in contrast, are generated by calling a remote API. This reduces local computation pressure and can simplify deployment on lightweight edge devices, but it requires network access and external service credentials. Therefore, choosing between HuggingFace and Cohere is not only a question of retrieval accuracy, but also a question of deployment constraints, response latency, operating cost, and system reliability.

        When storing embeddings in OpenGauss, the schema design should support both experimentation and later optimization. A practical table may include the original text content, the embedding vector, document identifier, chunk identifier, source file name, embedding model name, chunk size, overlap size, and creation time. Such metadata allows the engineer to compare different embedding models and chunking strategies without losing traceability. It also makes it easier to run controlled experiments because the retrieval result can be linked back to the exact preprocessing configuration used when the chunk was inserted into the database.

        Similarity search is the core operation of vector retrieval. Once query embeddings are generated, the system compares the query vector with stored chunk vectors and returns the nearest neighbors. In engineering practice, different distance operators may behave differently depending on whether vectors are normalized. Inner product, cosine distance, and Euclidean distance are all valid choices under different assumptions. For this reason, similarity operator selection should be part of the best-practice exploration rather than being fixed too early. Retrieval experiments should compare not only whether the system returns the correct chunk, but also whether the returned ranking is stable across different query types. Factoid questions, procedural questions, and summary questions may stress the retrieval system in different ways.

        A practical RetrievalQA system should separate retrieval evaluation from generation evaluation. Retrieval evaluation asks whether the database returns the correct or at least useful chunks. Typical indicators include top-1 hit rate, top-3 hit rate, mean reciprocal rank, and average retrieval latency. Generation evaluation asks whether the final answer is correct, grounded, and sufficiently complete. A system may retrieve the correct chunk but still produce a weak answer if the generation model fails to use the context properly. Conversely, a strong language model may sometimes produce a plausible answer even when retrieval is poor, which can hide defects in the retrieval layer. Therefore, both stages should be evaluated independently.

        BentoML can be used to package the retrieval and question answering logic as a deployable service. Instead of exposing raw Python scripts, the engineer can define a service interface such as ask(query: str) and let BentoML handle model packaging, dependency management, and API serving. This is especially useful when moving from experimentation to reproducible deployment. In the context of this project, BentoML serves as the application service layer rather than as an embedding model itself. It can wrap the chunker, embedder, database client, retriever, and answer generation logic into a single callable endpoint. This makes it easier to validate end-to-end behavior and later document the deployment procedure for community contribution.

        Containerization is another key part of the project. Docker makes it possible to package OpenGauss, Python runtime dependencies, and the BentoML service in a reproducible way. For development on standard Linux machines, this already simplifies environment setup. For deployment on AArch64 platforms, such as RK3568 boards, containerization becomes even more important because it reduces manual configuration drift across devices. However, containerization does not remove hardware constraints. On a lightweight board with limited memory and storage, not every model that works on a desktop environment will remain feasible. Therefore, the final deployment plan should distinguish between what is validated in a development environment and what is realistic on the target board.

        The RK3568 platform is a typical resource-constrained edge device. Its CPU performance and memory capacity are sufficient for lightweight services, databases, and controlled experiments, but they are not ideal for large embedding models and heavy generation models running simultaneously. In such an environment, a common production-style deployment strategy is to push offline preprocessing to a stronger machine. Large-scale document chunking, bulk embedding generation, and batch insertion can be completed on a development workstation or server. The edge device then focuses on online query handling, vector retrieval, and lightweight response assembly. This division of labor reduces memory pressure and improves stability. It also matches realistic edge deployment patterns where the edge node provides fast local search while heavy model computation remains centralized.

        For best-practice exploration, the project should test several dimensions systematically. The first dimension is chunking strategy. Fixed-length chunking is simple and easy to reproduce, but sentence-based or punctuation-based chunking may better preserve semantic boundaries. The second dimension is embedding backend. HuggingFace local embeddings provide more deployment autonomy, while Cohere embeddings may provide higher convenience or better hosted performance. The third dimension is retrieval parameter tuning, including top-k value, distance metric, and whether embeddings are normalized. The fourth dimension is deployment behavior, including container startup time, memory occupancy, response latency, and service stability under repeated queries. These dimensions together form the basis of a best-practice report rather than isolated coding experiments.

        A good test knowledge base should support multiple question types. Some questions should ask for definitions, such as what OpenGauss does in a RetrievalQA pipeline. Some should ask for process descriptions, such as how document chunking affects retrieval performance. Some should ask for comparisons, such as the difference between HuggingFace embeddings and Cohere embeddings. Some should ask for deployment reasoning, such as why a resource-constrained edge board should avoid heavy local generation models. If the knowledge base contains layered information like concepts, procedures, trade-offs, and deployment notes, then it becomes suitable for evaluating both retrieval accuracy and answer generation quality.

        When reporting results, the engineer should avoid describing the system as simply working or failing. Instead, the report should identify which configurations are recommended under which conditions. For example, a certain chunk size may work best for technical manuals, while a different overlap may help with fragmented deployment notes. A local HuggingFace embedding model may be suitable for offline experimentation, while Cohere may be more practical for remote or hybrid deployments. On RK3568, the recommended minimal solution may be to deploy OpenGauss and a lightweight service endpoint locally, while performing large-scale embedding generation on a separate machine. Such conclusions are more valuable than raw benchmark tables because they can guide future engineering decisions.

        The final project output should include several forms of deliverables. The first is a markdown deployment guide that describes environment preparation, container startup, database initialization, model configuration, and service verification. The second is Python example code that demonstrates document chunking, embedding insertion, vector retrieval, and end-to-end question answering. The third is a best-practice report that summarizes experiments, explains trade-offs, and recommends configurations for both standard Linux servers and AArch64 edge devices. The fourth is a community contribution package, such as a pull request or technical write-up, that makes the results reproducible for other developers interested in OpenGauss-based retrieval systems.

        An engineer maintaining this system should also be aware of operational details. Repeated reruns may create duplicate database records if the insertion pipeline is not idempotent. Model caches can consume large amounts of storage if they are not managed carefully. Mismatched database credentials between scripts, containers, and service code can cause failures that look like model errors but are actually environment configuration problems. For this reason, configuration files, environment variables, and deployment scripts should be standardized early. Even in a prototype stage, a clean project structure with separate modules for chunking, embedding, database access, retrieval, and service packaging greatly improves maintainability.

        In summary, an OpenGauss-based RetrievalQA project is not only about making a question answering demo. It is also about understanding the interaction between document preprocessing, embedding generation, vector retrieval, service packaging, and deployment constraints. HuggingFace, Cohere, and BentoML each play different roles in the system. OpenGauss provides the persistent vector storage and retrieval backbone. Chunking strategy determines how information is represented. Embedding models determine how semantics are mapped into vectors. Retrieval settings determine how relevant context is selected. BentoML turns the pipeline into a reusable service. Finally, the RK3568 deployment target introduces real-world constraints that force the system toward a minimal, stable, and well-justified implementation. This combination of system design, experimentation, and deployment reasoning is exactly what makes best-practice exploration meaningful.
        """

    def split_long_chunk_by_word(self, chunk):
        words_list = chunk.split()
        if not words_list:
            print("[ERROR] Empty long chunk to be split")
            return []

        sub_chunks = []
        current_chunks = []
        current_len = 0

        for word in words_list:
            add_len = len(word) if not current_chunks else len(word) + 1
            if current_len + add_len <= self.max_chunk_size:
                current_chunks.append(word)
                current_len += add_len
            else:
                if current_chunks:
                    sub_chunks.append(" ".join(current_chunks))

                if len(word) > self.max_chunk_size:
                    print(f"[WARNING] Long word detected: {word}")
                    sub_chunks.append(word)
                    current_chunks = []
                    current_len = 0
                else:
                    current_chunks = [word]
                    current_len = len(word)
        
        if current_chunks:
            sub_chunks.append(" ".join(current_chunks))
        
        return sub_chunks

    def split_initial_chunks(self, initial_chunks):
        current_chunks = []
        current_len = 0

        def joined_len(chunks):
            if not chunks:
                return 0
            return sum(len(chunk) for chunk in chunks) + len(chunks) - 1

        def flush_current_with_overlap():
            nonlocal current_chunks, current_len

            if not current_chunks:
                return

            text_chunk = " ".join(current_chunks)
            self.final_chunks.append(text_chunk)

            overlap_chunk = []
            overlap_len = 0
            for i in range(len(current_chunks)-1, -1, -1):
                candidate_len = len(current_chunks[i]) if not overlap_chunk else len(current_chunks[i]) + 1
                if overlap_len + candidate_len > self.overlap:
                    break
                else:
                    overlap_chunk.insert(0, current_chunks[i])
                    overlap_len += candidate_len

            current_chunks = overlap_chunk
            current_len = joined_len(current_chunks)


        for chunk in initial_chunks:
            chunk = chunk.strip()
            if not chunk:
                continue

            if len(chunk) > self.max_chunk_size:
                chunk_list = self.split_long_chunk_by_word(chunk)
            else:
                chunk_list = [chunk]

            for piece in chunk_list:
                piece_len = len(piece) if not current_chunks else len(piece) + 1
                if current_len + piece_len > self.max_chunk_size:
                    flush_current_with_overlap()
                    piece_len = len(piece) if not current_chunks else len(piece) + 1

                current_chunks.append(piece)
                current_len += piece_len

        if current_chunks:
            self.final_chunks.append(" ".join(current_chunks))

    def split_text_by_markers(self):
        import re
        joined_text = " ".join(s.strip() for s in self.knowledge_text_base.split("\n") if s.strip())
        initial_chunks = re.split(r'(?<=[.?!])\s+', joined_text)

        self.split_initial_chunks(initial_chunks)
        
    def split_text_by_length(self):
        initial_chunks = [s.strip() for s in self.knowledge_text_base.split("\n") if s.strip()]
        
        self.split_initial_chunks(initial_chunks)

    def split_text_into_dataset(self):
        from datasets import Dataset
        if self.cutting_type == "mark":
            self.split_text_by_markers()
        elif self.cutting_type == "length":
            self.split_text_by_length()
        else:
            raise ValueError(f"Unknown split method: {self.cutting_type}")

        db_dict = [{"text": chunk} for chunk in self.final_chunks]

        for i in range(min(4, len(db_dict))):
            print(f"== Chunk {i} ==\n{db_dict[i]}\n")
        
        db_dataset = Dataset.from_list(db_dict)
        db_dataset.save_to_disk(self.dataset_path)
        print(f"Dataset with {len(db_dataset)} chunks saved to {self.dataset_path}")

if __name__ == "__main__":
    text_chunker1 = TextChunker(max_chunk_size=150, overlap=0, cutting_type='mark', dataset_path="./data/kb_chunks_datasets_mark_150_0")
    text_chunker2 = TextChunker(max_chunk_size=150, overlap=20, cutting_type='mark', dataset_path="./data/kb_chunks_datasets_mark_150_20")
    text_chunker3 = TextChunker(max_chunk_size=150, overlap=50, cutting_type='mark', dataset_path="./data/kb_chunks_datasets_mark_150_50")
    text_chunker4 = TextChunker(max_chunk_size=200, overlap=0, cutting_type='mark', dataset_path="./data/kb_chunks_datasets_mark_200_0")
    text_chunker5 = TextChunker(max_chunk_size=200, overlap=20, cutting_type='mark', dataset_path="./data/kb_chunks_datasets_mark_200_20")
    text_chunker6 = TextChunker(max_chunk_size=200, overlap=50, cutting_type='mark', dataset_path="./data/kb_chunks_datasets_mark_200_50")
    text_chunker1.split_text_into_dataset()
    text_chunker2.split_text_into_dataset()
    text_chunker3.split_text_into_dataset()
    text_chunker4.split_text_into_dataset()
    text_chunker5.split_text_into_dataset()
    text_chunker6.split_text_into_dataset()